---
title: '2019-05-31: Blogdown afterthoughts'
author: 'Tom Hill'
  tags: [markdown, blogdown, website design]
fontsize: 13pt
---


### 2019-05-31: Blogdown afterthoughts

Having now tested out blogdown, I think I'm going to stick with basic R markdown for this site. Blogdown is incredibly powerful and has so many more options than basic markdown, but I just can't wrap my head around a lot of it. Blogdown has a much steeper learning curve, and I can't quite figure out what each section means. Like, why can I have a seperate page called 'courses' but not another name? If I add another page, or change its name, the website won't compile or load.

This site looks a lot more basic than it would with blogdown, but I also wouldn't be able to make this page as I can;t figure out how to have a blog not on the homepage. Again, maybe in the future I'll get past the learning curve and remake this page in blogdown. Boryana's guide was super useful and taught me a lot about website design and maintenance, as well as options in markdown and github, so glad I went over things with her.


-----

