---
fontsize: 13pt
---


### 2019-05-27: A Link Between Worlds

Next week, my fiance is leaving for Argentina for 6 weeks. Because of this, I was foolish enough to buy a new video game that I'm already absorbed into. Apparently I've only played bad Legend of Zelda games, as none of them have grabbed me before, but 'A Link Between Worlds' is phenomenal. As with most  Zelda games, it's an action RPG with lots of puzzles, but the game introduces a great new mechanic which literally adds another dimension to all of gameplay. Once you gain the ability to merge into walls (becoming 2D), you end up looking at every facet of the game (combat, puzzles, races, exploration) and wondering how it could be approached a different way, how could being 2D allow me to more effectively solve this problem. The transitions between 2D and 3D are also extremely fluid, not stopping the game cold like in Paper Mario. I'm already 1/4 of the way through after 2 days and will definitely be ordering another 3DS Zelda game to try out once I've finished.


-----

