---
fontsize: 13pt
---


### 2019-06-13 {.tabset}

####  <span>&#8203;</span>

#### K99 submission, Brandon Sanderson and dog sickness

Even though I finished my K99 last week, it wasn't actually submitted until yesterday. It was suprisingly stressful, as it turns out a lot of the formatting and required documents aren't really mentioned online, which resulted in lots of last minute changes, rushed paragraphs and poorly written letters. I was happy with the submission, though less so after the last minute cutting down. Here's hoping though!

I also finished the Mistborn series by Brandon Sanderson and have to say, those are fantastic books. The magic system he's created is comprehensive and interesting, based on gaining powers based on different types of consumed metals. I attempted to start reading his other big series, The StormLight Archives and have not been able to get inot these however. This feels much more of a standard fantasy series, with the magic not as well fleshed out. I'll power through, but if I had to recommend just one, Mistborn all the way.

While Dana is away I'm taking care of her dog. I'm not sure if it's stress or illness, but she's frustratingly not been eating her food consistently. Some days she'll eat normally, some days she'll only eatout of my hand, some days she'll only eat wet food. I'm taking her to the vets tomorrow and hopefully they'll be able to clarify some things.



